"""Inicial

Revision ID: 1419231d41b8
Revises: 
Create Date: 2026-04-06 08:01:24.537048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1419231d41b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_administradores_username'), ['username'], unique=True)

    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('valores_anteriores', sa.Text(), nullable=True),
    sa.Column('valores_nuevos', sa.Text(), nullable=True),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('valor_dia_defecto', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empleados_cedula'), ['cedula'], unique=True)

    op.create_table('bonos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bonos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bonos_empleado_id'), ['empleado_id'], unique=False)

    op.create_table('reportes_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('actividad', sa.Text(), nullable=False),
    sa.Column('valor_dia_original', sa.Float(), nullable=False),
    sa.Column('valor_dia_aplicado', sa.Float(), nullable=False),
    sa.Column('estado_pago', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id', 'fecha', name='uq_empleado_fecha')
    )
    with op.batch_alter_table('reportes_diarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reportes_diarios_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reportes_diarios_fecha'), ['fecha'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes_diarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reportes_diarios_fecha'))
        batch_op.drop_index(batch_op.f('ix_reportes_diarios_empleado_id'))

    op.drop_table('reportes_diarios')
    with op.batch_alter_table('bonos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bonos_empleado_id'))

    op.drop_table('bonos')
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empleados_cedula'))

    op.drop_table('empleados')
    op.drop_table('auditoria')
    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administradores_username'))

    op.drop_table('administradores')
    # ### end Alembic commands ###
